### ISSUE TITLE
save/load trained model ?

### ISSUE THREAD

**Issue by spate141** [abhaikollara/CNN-Sentence-Classification#2]
I have tried many of the classification approaches with TF, the one thing about saving trained model or the entire session or tf.variables are the only things which I can't figure out any easy way so I can load them back and use it to classify new data. Any thoughts ?

**Comment by abhaikollara** [comment]
I'm having difficulty understanding your question, although, have you checked out https://www.tensorflow.org/programmers_guide/variables#saving_and_restoring
